version: "3"

services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - redis
    volumes:
      - .:/home/node/code

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
