version: 2.1

jobs:
  build-and-test:
    working_directory: ~/app
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Deps
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint Code
          command: npm run lint
      - run:
          name: Run Tests
          command: npm run test

workflows:
    build-and-test:
      jobs:
        - build-and-test
